site_name: Divine Steam 2

theme:
    name: material
    palette:
      scheme: slate
    # sidebar_color: '#f1f5f9'
    favicon: img/favicon.ico
    features:
        - navigation.tabs
        # - navigation.footer
        - toc.integrate
        - content.code.annotate
        # - navigation.instant
        # - navigation.expand
        # - content.tabs.link

# extra_css:
#   - stylesheets/extra.css

use_directory_urls: false

plugins:
    - search
    - mermaid2
    - awesome-nav
    # - awesome-pages
