site_name: Divine Steam

theme:
    name: material
    # palette:
    #   scheme: slate
    # sidebar_color: '#f1f5f9'
    favicon: img/favicon.ico
    features:
        - navigation.tabs
        - navigation.footer
        # - toc.integrate
        # - content.code.annotate

        # - navigation.instant
        - navigation.expand
        # - content.tabs.link


    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: pink
        accent: black
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: pink
        accent: black
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

# extra_css:
#   - stylesheets/extra.css

use_directory_urls: false

plugins:
    - search
    - mermaid2
    - awesome-nav
    # - awesome-pages